# Site settings
title: anthroviz Composition Book
email: cherylwu@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  Cheryl Wu's notes for undergraduate NYU Gallatin concentration
baseurl: "/compbook/" # the subpath of your site, e.g. /blog/
url: "http://grungerabbit.com" # the base hostname & protocol for your site
twitter_username: grungerabbit
github_username:  grungerabbit

# Build settings
markdown: kramdown
